FROM ubuntu:latest

RUN apt-get update && apt-get install -y vsftpd && apt-get install -y python3 && apt-get install -y python3-pip

RUN pip install PyJWT
RUN pip install flask

RUN apt-get install -y iputils-ping

WORKDIR /app

COPY . /app

ENV FLASK_APP=/app/app.py
ENV FLASK_ENV=development

CMD [ "flask", "run", "--host=0.0.0.0" ]
