# Usar la imagen oficial de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar los archivos del proyecto al contenedor
COPY . .

# Instalar las dependencias necesarias
RUN pip install flask
RUN pip install PyJWT
RUN apt update
RUN apt install sqlite3

RUN rm database.db
RUN cp original_database.db database.db

# Exponer el puerto 5000 para acceder a la aplicación Flask
EXPOSE 5000

# Comando para iniciar la aplicación Flask
CMD ["python", "app.py"]