# Imagen base de Python
FROM python:3.9-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el código fuente al contenedor
COPY . .

# Exponer el puerto 4040 para el servidor socket
EXPOSE 4040

# Comando para ejecutar la aplicación Python
CMD ["python", "main.py"]
